apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    project: roboshop
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: http-web-svc



