apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    project: roboshop
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: http-web-svc

"""
You're trying to curl the ClusterIP of your nginx-service, which works only from within the cluster, not from your EC2 host (outside the cluster). That’s why the curl command is hanging—it's not reachable externally.

💡 Explanation:
Your service nginx-service is of type ClusterIP, which is only accessible from within the Kubernetes cluster.

From the EC2 host terminal (even if on the same VPC), it's not able to hit the ClusterIP directly.

✅ How to test it correctly:
Option 1: curl from inside a pod
kubectl exec -it demo-env -- curl 10.100.43.175
This should work, as you're curling from inside the cluster.

kubectl exec -it nginx -- curl nginx-service # we will call with service names , bcz service ip's are ephermeral

"""


