apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort # Expose the service on a node port
  selector:
    app: nginx-nodeport # Match the pod's label
  ports:
  - port: 80 # The port the service exposes
    targetPort: 80 # The port your application listens on
    protocol: TCP
    nodePort: 30000 # Choose a node port (e.g., 30000)
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-nodeport
spec:
  containers:
  - name: my-app-container
    image: nginx # Replace with your application's image
    ports:
    - containerPort: 80 # The port your application listens on