apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: hitesh2201/fluentd:v1.12-debian
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluentd.conf  # This ensures that only the file is mounted
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config  # The name of your ConfigMap
