apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/messages
      pos_file /var/log/fluentd-test.pos
      tag test.logs
      format none
      read_from_head true
    </source>

    <match kubernetes.**>
      @type cloudwatch_logs
      log_group_name "fluentd-logs"
      log_stream_name "fluentd-log-stream"
      region "us-east-1"
      auto_create_group true
      auto_create_stream true
      <buffer>
        flush_interval 5s
        flush_at_shutdown true
      </buffer>
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: hitesh2201/fluentd:v1.12
          imagePullPolicy: Always
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluentd.conf
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
