apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  persistentVolumeReclaimPolicy: "Retain"
  resources:
    requests:
      storage: 1Gi
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-dynamic
  labels:
    app: ebs-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebs-dynamic
  template:
    metadata:
      labels:
        app: ebs-dynamic
    spec:
      containers:
      - name: ebs-dynamic
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
      nodeSelector:
        zone: 1d
      volumes:
      - name: nginx-data
        persistentVolumeClaim:
          claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    app: ebs-dynamic
  ports:
    - port: 80           # Port exposed by the service
      targetPort: 80     # Port your container listens on