apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
