apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password